version: "4.0"

services:
  postgres:
    image: postgres:15-alpine
    container_name: yolo_postgres
    environment:
      POSTGRES_DB: yolo_db
      POSTGRES_USER: yolo_user
      POSTGRES_PASSWORD: yolo_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - yolo_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: yolo_backend
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: yolo_db
      DB_USERNAME: yolo_user
      DB_PASSWORD: yolo_password
      JWT_SECRET: dev-jwt-secret
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - yolo_network
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: yolo_frontend
    environment:
      - NODE_ENV=development
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - yolo_network
    command: npm start

volumes:
  postgres_data:
    driver: local

networks:
  yolo_network:
    driver: bridge
